### ISSUE TITLE
Review Kanban Project Setup

### ISSUE THREAD

**Issue by ahangarha** [ahangarha/JavaScript-Capstone#32]
Hi

We are two teammates (@daudi13 and @ahangarha) and here is the link to the Kanboard project of this repository:
https://github.com/ahangarha/JavaScript-Capstone/projects/1

**Comment by Dipeshtwis** [comment]
Hi @ahangarha & @daudi13, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

## Required Changes ♻️

- [x] For a team with two people - The number of cards on board should be equal to 15, but you have a total of 17 cards. Please remove those cards. 
You have included a new card named `Install and config webpack` but you have already a similar card `Setup the project with webpack ....`.

![Screenshot from 2022-03-07 20-22-31](https://user-images.githubusercontent.com/22434660/157057948-bfb8cf0d-4eb7-46aa-813b-671f6998fc97.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N.A.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ahangarha** [comment]
@Dipeshtwis Thank you for your review.

The extra issues are added intentionally since we have made a decision of implementing the final design at the end of the project.

If this is not allowed, please let us know so that we remove them.

**Comment by Dipeshtwis** [comment]
> @Dipeshtwis Thank you for your review.
> 
> The extra issues are added intentionally since we have made a decision of implementing the final design at the end of the project.
> 
> If this is not allowed, please let us know so that we remove them.

Hi @ahangarha,

Thank you for asking.
Let me answer it as one of them is similar which I've already mentioned. For the other card, I would recommend making a design step by step as it would be better to do it like that, and in the final, you can fix a little bit of issue if occur. In this way, you don't have to give extra time while making a design. So It's better to remove those two cards.

Hope you will understand.
Thank You. :slightly_smiling_face:

**Comment by BrianSammit** [comment]
# STATUS: APPROVED :green_circle: :clap: 

Hello team 👋, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ahangarha** [comment]
Thank you @BrianSammit. I just wanted to mention this is an Issue not PR :wink:
